assets:
  - lisas.sql.gz
steps:
  - name: Setup Drupal site
    plugin: Drupal
    database: lisas.sql.gz
    databaseGzipped: true
    revertFeatures: true
    fileProxy: https://example.com
  - name: Generate login link
    command: 'drush uli admin'
