image: lampin-latest
proboBaseImage: proboci/ubuntu-14.04-lamp
steps:
  - name: Update database
    command: drush updb -y
  - name: Revert features
    command: drush cc all
  - name: Clear caches
    command: drush cc all
  - name: Generate login link
    command: 'drush uli admin'
